export const productList = [
    {
      id: 1,
      name: "PC/CPU ACER VERITON Intel Seri G2020 GEN 3",
      price: 800000,
      category: "CPU",
      description: "Acer PurifiedVoice (Noise Cancellation)\n\nOHS: Office Home & Student 2021\n\nCPU: Intel N100 processor (4 Cores, 3.4 GHz)\n\nOS: Windows 11 Home\n\nLCD: \"14.0\" FHD 1920 x 1080, Acer ComfyView™\n\nLED-backlit TFT LCD\"\n\nMemory: 8 GB LPDDR5\n\nHardisk : 512 GB SSD NVMe Gen4\n\nGraphic : Intel® UHD Graphics\n\nBluetooth: Bluetooth® 5.0\n\nWifi:\n\n• 802.11a/b/g/n/ac+ax wireless LAN\n\n• Operates at 2.4 GHz and 5 GHz\"\n\nCamera :\n\nHD webcam with Acer Temporal Noise Reduction :\n\n1280 x 720 resolution;\n\n720p HD audio/video recording\n\nSpeaker: Two built-in stereo speakers\n\nI/O Port :\n\n2x USB 3.2 Gen 1\n\n1x USB Type-C (Full Function : DC-In, Charge, Data, Display)\n\nHDMI® port 2.0 with HDCP support\n\nAccessory: Acer Carrying Bag\n\nWarranty: 1/3/0 (Part/Labour/Onsite)\n\nColor Variant: Pure Silver",
    },
    {
      id: 2,
      name: "ACER KEYBOARD MECHANICAL GAMING PREDATOR AETHON 300 [NP.KBD1A.024]",
      price: 1000000,
      category: "Keyboard",
      description: "Switch Type: Cherry Switches (MX Blue)\n\nWired\n\nABS top cover + ABS bottom case\n\nDurability: Over 50M actuations\n\nReport Rate: 1ms/1000hz\n\nBacklight: \"single color(Teal Blue) 9 lighting effects : Lightened/ Breathing/wave / Spin/ Trigger Ripple 1/ Trigger Single /Trigger Laser Beam/Rain Drop/Trigger Ripple 2/ Rectangle Grid)\"\n\nLED Indicators: Win kby lock, Num Lock, Caps Lock\n\n100% anti-ghosting\n\nCombo Multimedia Keys",
    },
    {
      id: 3,
      name: "Acer Aspire 3 Slim (A314-36P)",
      price: 6000000,
      category: "Laptop",
      description: "Acer PurifiedVoice (Noise Cancellation)\n\nOHS: Office Home & Student 2021\n\nCPU: Intel N100 processor (4 Cores, 3.4 GHz)\"\n\nOS: Windows 11 Home\n\nLCD: \"14.0\" FHD 1920 x 1080, Acer ComfyView™\n\nLED-backlit TFT LCD\"\n\nMemory: 8 GB LPDDR5\n\nHardisk : 512 GB SSD NVMe Gen4\n\nGraphic : Intel® UHD Graphics\n\nBluetooth: Bluetooth® 5.0\n\nWifi:\n\n• 802.11a/b/g/n/ac+ax wireless LAN\n\n• Operates at 2.4 GHz and 5 GHz\"\n\nCamera :\n\nHD webcam with Acer Temporal Noise Reduction :\n\n1280 x 720 resolution;\n\n720p HD audio/video recording\n\nSpeaker: Two built-in stereo speakers\n\nI/O Port :\n\n2x USB 3.2 Gen 1\n\n1x USB Type-C (Full Function : DC-In, Charge, Data, Display)\n\nHDMI® port 2.0 with HDCP support\n\nAccessory: Acer Carrying Bag\n\nWarranty: 1/3/0 (Part/Labour/Onsite)\n\nColor Variant: Pure Silver",
    },
    {
      id: 4,
      name: "ACER MONITOR 23.8 INCH ACER NITRO QG240Y_S3 | FHD 180HZ",
      price: 800000,
      category: "Monitor",
      description: "Display: 23.8\" VA Zero Frame, Full HD (1920x1080)@180Hz\n\nResponse Time: 1ms(VRB)\n\nInput Interface: HDMI(2.0) + DisplayPort(1.4) + Audio out\n\nFeatures: sRGB 95%, HDR10, 6-Axis Color Adjustment, Super Sharpness, Bluelight Shield, Flicker Free, Comfyview, Low Dimming, Ultra low latency, Dark/Black Boost, Display Widget dan Desain Ergonomis",
    },
    {
      id: 5,
      name: "ACER PREDATOR MOUSE CESTUS 320 GAMING MOUSE",
      price: 500000,
      category: "Mouse",
      description: "Wired 1.8m cable\n\n5 million clicks\n\nMax 6500 DPI\n\nSensor Pixart 3325\n\n16.8 millions RGB color\n\n6 Programmable Button",
    },
    {
      id: 6,
      name: "ASUS VivoBook A416MAO-FHD425",
      price: 5000000,
      category: "Laptop",
      description: "Operating System: Windows 11 Home - ASUS recommends Windows 11 Pro for business\n\nOffice: Office Home and Student 2021 included\n\nLCD cover-material: Plastic\n\nLCD cover-color: Transparent Silver\n\nTop case-material: Plastic\n\nPanel Size: 14.0\" (16:9) FHD (1920x1080) Anti-Glare 60Hz Panel with 45% NTSC\n\nProcessor: Intel® Celeron® N4020 Processor 1.1 GHz (4M Cache, up to 2.8 GHz, 2 cores)\n\nIntergrated GPU: Intel® UHD Graphics 600\n\nTotal System Memory: 4GB DDR4 SO-DIMM\n\nStorage: 256GB M.2 NVMe™ PCIe® 3.0 SSD + HDD housing for storage expansion\n\nOptical Drive: N/A\n\nFront-facing camera: VGA camera\n\nWireless: Wi-Fi 5(802.11ac)+Bluetooth 4.1 (Dual band) 1*1\n\nKeyboard type: Backlit Chiclet Keyboard\n\nNumberPad: N/A\n\nScreenPad™: N/A\n\nFingerPrint: N/A\n\nI/O ports:\n\n1x HDMI 1.4\n\n1x 3.5mm Combo Audio Jack\n\n1x DC-in//1x USB 3.2 Gen 1 Type-A\n\n1x USB 3.2 Gen 1 Type-C\n\n2x USB 2.0 Type-A\n\nAudio:\n\nSonicMaster\n\nBuilt-in speaker\n\nBuilt-in microphone\n\nVoice control with Cortana support\n\nAC Adapter: ø4.0, 33W AC Adapter, Output: 19V DC, 1.75A, 33W, Input: 100-240V AC 50/60Hz universal\n\nBattery: 37WHrs, 2S1P, 2-cell Li-ion\n\nReplaceable Battery: No\n\nDimension (WxHxD): 32.54 x 21.60 x 1.99 cm\n\nWeight (with Battery): 1.60 kg",
    },
    {
      id: 7,
      name: "ASUS Wireless Mouse WT200",
      price: 300000,
      category: "Mouse",
      description: "Special Feature: Wireless, Ergonomic, Optical. Bentuk ergonomis memungkinkan penggunaan tangan kiri dan kanan. Mouse ini dirancang untuk menahan 3 juta klik. Resolusi mouse adalah 1200 dpi, yang membuatnya sangat akurat digunakan. Mouse ini dilengkapi dengan Teknologi Komunikasi 2.4GHz. Fitur pelacakan optik canggih memungkinkan gerakan ultra presisi pada hampir semua permukaan. Kompatibel dengan Windows 7, 8, dan 10.",
    },
    {
      id: 8,
      name: "HP Laptop 14-em0014AU Ryzen 3-7320",
      price: 7000000,
      category: "Laptop",
      description: "Operating system: Windows 11 Home Single Language\n\nProcessor family: AMD Ryzen™ 3 processor\n\nProcessor: AMD Ryzen™ 3 7320U (up to 4.1 GHz max boost clock, 4 MB L3 cache, 4 cores, 8 threads)\n\nChipset: AMD integrated SoC\n\nSecurity management: Mic mute key; Camera privacy shutter; Trusted Platform Module (Firmware TPM) support\n\nMemory: 8 GB LPDDR5-6400 MHz RAM (onboard)\n\nMemory layout (slots & size): onboard\n\nInternal Storage: 512 GB PCIe® NVMe™ M.2 SSD\n\nCloud service: 25 GB Dropbox storage for 12 months\n\nDisplay: 35.6 cm (14\") diagonal, FHD (1920 x 1080), micro-edge, anti-glare, 250 nits, 45% NTSC\n\nGraphics: Integrated\n\nGraphics (integrated): AMD Radeon™ Graphics\n\nPorts: 1 USB Type-C® 5Gbps signaling rate; 2 USB Type-A 5Gbps signaling rate; 1 HDMI 1.4b; 1 AC smart pin; 1 headphone/microphone combo\n\nCamera: HP True Vision 1080p FHD camera with temporal noise reduction and integrated dual array digital microphones\n\nAudio: Dual speakers\n\nPointing device: HP Imagepad\n\nKeyboard: Full-size, backlit, soft grey keyboard\n\nWireless: Realtek Wi-Fi 6 (1x1) and Bluetooth® 5.3 wireless card\n\nPower supply type: 45 W Smart AC power adapter\n\nBattery type: 3-cell, 41 Wh Li-ion polymer\n\nEcolabels: EPEAT® registered\n\nEnergy star certified: ENERGY STAR® certified\n\nProduct design: Matte paint finish cover and keyboard frame, textured base\n\nProduct color: Natural silver\n\nMinimum dimensions (W x D x H): 32.37 x 21.5 x 1.79 (front) – 3.25 (rear) cm (Dimensions vary by configuration)\n\nWeight: 1.4 kg\n\nUPC number: 197192650257\n\nPackage dimensions (W x D x H): 6.9 x 48.3 x 30.5 cm\n\nPackage weight: 2 kg\n\nSoftware included: McAfee LiveSafe™",
    },
    {
      id: 9,
      name: "HP Monitor 24FWA",
      price: 2000000,
      category: "Monitor",
      description: "Display size (diagonal): 23.8\"\n\nDisplay type: IPS\n\nResolution (native): FHD (1920 x 1080 @ 75 Hz)\n\nPixel pitch: 0.275 mm\n\nBrightness: 300 nits\n\nContrast ratio: 1000:1\n\nResponse time: 5 ms\n\nDisplay Input Type: 1 VGA; 1 HDMI 1.4 (with HDCP support)",
    },
    {
      id: 10,
      name: "HP DeskJet Ink Advantage 2337",
      price: 900000,
      category: "Printer",
      description: "Sku: 7WQ07B\n\nPrint Speed, Black: <=10\n\nColor Or Black: Color\n\nPrint Speed, Color: <=10\n\nProduct Types: Inkjet printers\n\nFamily Brand: Deskjet\n\nPerfect For: Home\n\nUsage: Student, Primary, Home and home office\n\nFeatures: Scan to PDF\n\nFunctions: Print scan and copy\n\nFinished Output Handling: Sheetfed\n\nEnvelope Input Capacity: Up to 5 envelopes\n\nOutput Capacity: Up to 25 sheets\n\nMaximum Output Capacity (Sheets): Up to 25 sheets\n\nPaper Handling Input, Standard: 60-sheet input tray\n\nInput Capacity: Up to 60 sheets\n\nPaper Handling Output, Standard: 25-sheet output tray",
    },
    {
      id: 11,
      name: "Lenovo Legion KM300 RGB",
      price: 1000000,
      category: "Keyboard",
      description: "Set Bundle: Ya\n\nTipe Pengunci Keyboard: Membrane Key\n\nGaming: Ya\n\nJenis Garansi: Garansi Resmi Lenovo Indonesia\n\nModel Keyboard & Mouse: Legion KM300 RGB Gaming Combo Wired\n\nKesesuaian Keyboard: Wired via USB2.0\n\nMasa Garansi: 1 Tahun\n\nDimensi (P x L x T): Packed 550 x 198 x 52 mm",
    },
    {
      id: 12,
      name: "Lenovo V14 G2",
      price: 6000000,
      category: "Laptop",
      description: "Ukuran Layar Laptop: 14 inci\n\nTipe Laptop: Ultrabook, Terjangkau, Non-touch, Clamshell\n\nKapasitas Penyimpanan: 256GB\n\nTipe Panel: TN, 14\" HD (1366x768), 250nits, 45% NTSC, Antiglare\n\nJenis Penyimpanan: SSD\n\nPorts/Interface: Combo Headphone/Mic, Ethernet LAN, HDMI, USB 2.0, USB 3.2\n\nOptical Disk Drive: Tidak\n\nKondisi: Baru\n\nSistem Operasi: Windows 11 Home 64 SL, English\n\nModel Laptop: Lenovo V14 G2 ALC\n\nProdusen Chipset Grafis: Integrated AMD Radeon Graphics\n\nFrekuensi CPU: 2.6Ghz\n\nJenis Garansi: Garansi Resmi Lenovo Indonesia\n\nKapasitas Baterai: 38Wh\n\nMasa Garansi: 2 Tahun Courier or Carry-in\n\nTipe Prosesor: AMD Ryzen 3 5300U\n\nBerat Produk: 1.6kg\n\nJumlah Core: 4 Cores / 8 Threads\n\nDimensi (P x L x T): 324.2 x 215.2 x 19.9 mm",
    },
    {
      id: 13,
      name: "Lenovo Monitor L22e-40",
      price: 2000000,
      category: "Monitor",
      description: "DISPLAY\n\nPanel Size: 21.45-inch\n\nScreen Dimensions: 488.1 mm x 270.5 mm\n\nCONNECTIVITY\n\nVideo Signal:\n\n• 1 x HDMI 1.4\n\n• 1 x VGA\n\nAudio Signal:\n\n• 1 x Audio Out (3.5 mm)\n\nSPECIAL FEATURES\n\nSoftware: Lenovo Artery (Lenovo Display Control Center)\n\nSync Technology: AMD FreeSync\n\nNatural Low Blue Light: Yes\n\nPOWER\n\nPower Consumption (Typ. / Max): 15.0W / 20.5W\n\nMECHANICAL\n\nTilt Angle (Front / Back): -5°/ 22°\n\nVESA Mount Capability: Yes (100 x 100 mm)\n\nDIMENSION\n\nSize Packed (D x H x W) (mm/inch): 117.0 x 353.0 x 588.0 mm / 4.61 x 13.90 x 23.15 inches",
    },
    {
      id: 14,
      name: "Lenovo 530 Wireless Mouse",
      price: 300000,
      category: "Mouse",
      description: "Tipe Koneksi: Wireless\n\nGaming: Tidak\n\nSet Bundle: Tidak\n\nMasa Garansi: 12 Bulan\n\nJenis Garansi: Garansi Resmi Lenovo Indonesia\n\nModel Keyboard & Mouse: Lenovo 530 Wireless Mouse\n\nKesesuaian Mouse: 2.4 GHz Wireless via Nano USB Type-A\n\nDimensi (P x L x T): Net 63 x 106 x 37 mm",
    },
    {
      id: 15,
      name: "Samsung Chromebook 4",
      price: 3000000,
      category: "Laptop",
      description: "Ukuran Layar Laptop: < 13 inci\n\nTipe Laptop: 2-in-1, Kerja, Sekolah\n\nKapasitas Penyimpanan: 32GB\n\nKondisi: Baru\n\nMasa Garansi: 12 Bulan\n\nJenis Garansi: GARANSI SAMSUNG INDONESIA\n\nModel Laptop: Chromebook 4\n\nJenis Penyimpanan: MMC Micro sd",
    },
    {
      id: 16,
      name: "Samsung Mouse USB Wireless",
      price: 40000,
      category: "Mouse",
      description: "Slim ergonomis dirancang dengan 2.4 GHz mouse nirkabel, ideal untuk rumah atau kantor\n\nKompatibel dengan kebanyakan laptop dan komputer desktop via USB receiver (dikemas dalam mouse)\n\nTeknologi pelacakan optik, bekerja pada distribusi permukaan\n\n16 saluran kerja nirkabel, frekuensi otomatis melompat\n\nFrekuensi: 2402 MHz-2480 MHz\n\nWi-Fi Range: 10m",
    },
  ]
