export const productList = [
    {
      id: 1,
      name: "ACER CPU",
      price: 19.99,
      category: "CPU",
      description: "A high-quality electronic product.",
    },
    {
      id: 2,
      name: "Acer Keyboard",
      price: 29.99,
      category: "Keyboard",
      description: "A stylish piece of clothing.",
    },
    {
      id: 3,
      name: "Acer Laptop",
      price: 9.99,
      category: "Laptop",
      description: "A useful kitchen gadget.",
    },
    {
      id: 4,
      name: "Acer Monitor",
      price: 49.99,
      category: "Monitor",
      description: "A cutting-edge electronic device.",
    },
    {
      id: 5,
      name: "Acer Mouse",
      price: 14.99,
      category: "Mouse",
      description: "A best-selling book.",
    },
    {
      id: 6,
      name: "Asus Laptop",
      price: 39.99,
      category: "Laptop",
      description: "Fashionable clothing item.",
    },
    {
      id: 7,
      name: "Asus Mouse",
      price: 7.99,
      category: "Mouse",
      description: "Beautiful home decor accessory.",
    },
    {
      id: 8,
      name: "Hp Laptop",
      price: 59.99,
      category: "Laptop",
      description: "An advanced electronic gadget.",
    },
    {
      id: 9,
      name: "Hp Monitor",
      price: 24.99,
      category: "Monitor",
      description: "Premium beauty product.",
    },
    {
      id: 10,
      name: "Hp Printer",
      price: 12.99,
      category: "Printer",
      description: "Fun and interactive toy.",
    },
    {
      id: 11,
      name: "Lenovo Keyboard",
      price: 12.99,
      category: "Keyboard",
      description: "Fun and interactive toy.",
    },
    {
      id: 12,
      name: "Lenovo Laptop",
      price: 12.99,
      category: "Laptop",
      description: "Fun and interactive toy.",
    },
    {
      id: 13,
      name: "Lenovo Monitor",
      price: 12.99,
      category: "Monitor",
      description: "Fun and interactive toy.",
    },
    {
      id: 14,
      name: "Lenovo Mouse",
      price: 12.99,
      category: "Mouse",
      description: "Fun and interactive toy.",
    },
    {
      id: 15,
      name: "Samsung Laptop",
      price: 12.99,
      category: "Laptop",
      description: "Fun and interactive toy.",
    },
    {
      id: 16,
      name: "Samsung Mouse",
      price: 12.99,
      category: "Mouse",
      description: "Fun and interactive toy.",
    },
  ];
  